In [1]:
import pandas as pd 

# To perform numerical operations
import numpy as np

# To visualize data
import seaborn as sns

# To partition the data
from sklearn.model_selection import train_test_split

# Importing library for logistic regression
from sklearn.linear_model import LogisticRegression

# Importing performance metrics - accuracy score & confusion matrix
from sklearn.metrics import accuracy_score,confusion_matrix

In [2]:
data_income = pd.read_csv(r'C:\Users\ruchi\Videos\Data_Science\nptel\income(1).csv')
data_income.head()

age       JobType         EdType        maritalstatus       occupation  \
0   45       Private        HS-grad             Divorced     Adm-clerical   
1   24   Federal-gov        HS-grad        Never-married     Armed-Forces   
2   44       Private   Some-college   Married-civ-spouse   Prof-specialty   
3   27       Private            9th        Never-married     Craft-repair   
4   20       Private   Some-college        Never-married            Sales   

      relationship    race   gender  capitalgain  capitalloss  hoursperweek  \
0    Not-in-family   White   Female            0            0            28   
1        Own-child   White     Male            0            0            40   
2          Husband   White     Male            0            0            40   
3   Other-relative   White     Male            0            0            40   
4    Not-in-family   White     Male            0            0            35   

    nativecountry                        SalStat  
0   United-States   less than or equal to 50,000  
1   United-States   less than or equal to 50,000  
2   United-States            greater than 50,000  
3          Mexico   less than or equal to 50,000  
4   United-States   less than or equal to 50,000

In [3]:
data = data_income.copy()

In [4]:
print(data.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 31978 entries, 0 to 31977
Data columns (total 13 columns):
 #   Column         Non-Null Count  Dtype 
---  ------         --------------  ----- 
 0   age            31978 non-null  int64 
 1   JobType        31978 non-null  object
 2   EdType         31978 non-null  object
 3   maritalstatus  31978 non-null  object
 4   occupation     31978 non-null  object
 5   relationship   31978 non-null  object
 6   race           31978 non-null  object
 7   gender         31978 non-null  object
 8   capitalgain    31978 non-null  int64 
 9   capitalloss    31978 non-null  int64 
 10  hoursperweek   31978 non-null  int64 
 11  nativecountry  31978 non-null  object
 12  SalStat        31978 non-null  object
dtypes: int64(4), object(9)
memory usage: 3.2+ MB
None


In [5]:
data.isnull()          
       

age  JobType  EdType  maritalstatus  occupation  relationship   race  \
0      False    False   False          False       False         False  False   
1      False    False   False          False       False         False  False   
2      False    False   False          False       False         False  False   
3      False    False   False          False       False         False  False   
4      False    False   False          False       False         False  False   
...      ...      ...     ...            ...         ...           ...    ...   
31973  False    False   False          False       False         False  False   
31974  False    False   False          False       False         False  False   
31975  False    False   False          False       False         False  False   
31976  False    False   False          False       False         False  False   
31977  False    False   False          False       False         False  False   

       gender  capitalgain  capitalloss  hoursperweek  nativecountry  SalStat  
0       False        False        False         False          False    False  
1       False        False        False         False          False    False  
2       False        False        False         False          False    False  
3       False        False        False         False          False    False  
4       False        False        False         False          False    False  
...       ...          ...          ...           ...            ...      ...  
31973   False        False        False         False          False    False  
31974   False        False        False         False          False    False  
31975   False        False        False         False          False    False  
31976   False        False        False         False          False    False  
31977   False        False        False         False          False    False  

[31978 rows x 13 columns]

In [6]:
print('Data columns with null values:\n', data.isnull().sum())
#**** No missing values !

Data columns with null values:
 age              0
JobType          0
EdType           0
maritalstatus    0
occupation       0
relationship     0
race             0
gender           0
capitalgain      0
capitalloss      0
hoursperweek     0
nativecountry    0
SalStat          0
dtype: int64


In [7]:
summary_num = data.describe()
print(summary_num) 

                age   capitalgain   capitalloss  hoursperweek
count  31978.000000  31978.000000  31978.000000  31978.000000
mean      38.579023   1064.360623     86.739352     40.417850
std       13.662085   7298.596271    401.594301     12.345285
min       17.000000      0.000000      0.000000      1.000000
25%       28.000000      0.000000      0.000000     40.000000
50%       37.000000      0.000000      0.000000     40.000000
75%       48.000000      0.000000      0.000000     45.000000
max       90.000000  99999.000000   4356.000000     99.000000


In [8]:
summary_cate = data.describe(include = "O")
print(summary_cate)

         JobType    EdType        maritalstatus       occupation relationship  \
count      31978     31978                31978            31978        31978   
unique         9        16                    7               15            6   
top      Private   HS-grad   Married-civ-spouse   Prof-specialty      Husband   
freq       22286     10368                14692             4038        12947   

          race gender   nativecountry                        SalStat  
count    31978  31978           31978                          31978  
unique       5      2              41                              2  
top      White   Male   United-States   less than or equal to 50,000  
freq     27430  21370           29170                          24283  


In [9]:
data['JobType'].value_counts()
data['occupation'].value_counts()

occupation
Prof-specialty       4038
Craft-repair         4030
Exec-managerial      3992
Adm-clerical         3721
Sales                3584
Other-service        3212
Machine-op-inspct    1966
?                    1816
Transport-moving     1572
Handlers-cleaners    1350
Farming-fishing       989
Tech-support          912
Protective-serv       644
Priv-house-serv       143
Armed-Forces            9
Name: count, dtype: int64

In [10]:
print(np.unique(data['JobType'])) 
print(np.unique(data['occupation']))

[' ?' ' Federal-gov' ' Local-gov' ' Never-worked' ' Private'
 ' Self-emp-inc' ' Self-emp-not-inc' ' State-gov' ' Without-pay']
[' ?' ' Adm-clerical' ' Armed-Forces' ' Craft-repair' ' Exec-managerial'
 ' Farming-fishing' ' Handlers-cleaners' ' Machine-op-inspct'
 ' Other-service' ' Priv-house-serv' ' Prof-specialty' ' Protective-serv'
 ' Sales' ' Tech-support' ' Transport-moving']


In [11]:
data = pd.read_csv(r'C:\Users\ruchi\Videos\Data_Science\nptel\income(1).csv',na_values=[" ?"]) 

In [12]:
data.isnull().sum()

age                 0
JobType          1809
EdType              0
maritalstatus       0
occupation       1816
relationship        0
race                0
gender              0
capitalgain         0
capitalloss         0
hoursperweek        0
nativecountry       0
SalStat             0
dtype: int64

In [13]:
missing = data[data.isnull().any(axis=1)]

In [14]:
data2 = data.dropna(axis=0)
data3 = data2.copy()
data4 = data3.copy()


In [16]:
# Realtionship between independent variables
correlation = data2.corr(numeric_only=True)

In [17]:
data2.columns

Index(['age', 'JobType', 'EdType', 'maritalstatus', 'occupation',
       'relationship', 'race', 'gender', 'capitalgain', 'capitalloss',
       'hoursperweek', 'nativecountry', 'SalStat'],
      dtype='object')

In [20]:
gender = pd.crosstab(index = data2["gender"], columns  = 'count', normalize = True)
print(gender)
# =============================================================================
#  Gender vs Salary Status:
# =============================================================================




col_0      count
gender          
Female  0.324315
Male    0.675685


In [21]:
gender_salstat = pd.crosstab(index = data2["gender"],columns = data2['SalStat'], margins = True, normalize =  'index') 
                 # Include row and column totals
print(gender_salstat)

SalStat  greater than 50,000  less than or equal to 50,000
gender                                                    
 Female             0.113678                      0.886322
 Male               0.313837                      0.686163
All                 0.248922                      0.751078


In [22]:
# Reindexing the salary status names to 0,1
data2['SalStat']=data2['SalStat'].map({' less than or equal to 50,000':0,' greater than 50,000':1})
print(data2['SalStat'])


0        0
1        0
2        1
3        0
4        0
        ..
31973    0
31974    0
31975    0
31976    0
31977    0
Name: SalStat, Length: 30162, dtype: int64


C:\Users\ruchi\AppData\Local\Temp\ipykernel_15892\4183655042.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data2['SalStat']=data2['SalStat'].map({' less than or equal to 50,000':0,' greater than 50,000':1})


In [23]:
new_data=pd.get_dummies(data2, drop_first=True)

In [24]:
columns_list=list(new_data.columns)
print(columns_list)

['age', 'capitalgain', 'capitalloss', 'hoursperweek', 'SalStat', 'JobType_ Local-gov', 'JobType_ Private', 'JobType_ Self-emp-inc', 'JobType_ Self-emp-not-inc', 'JobType_ State-gov', 'JobType_ Without-pay', 'EdType_ 11th', 'EdType_ 12th', 'EdType_ 1st-4th', 'EdType_ 5th-6th', 'EdType_ 7th-8th', 'EdType_ 9th', 'EdType_ Assoc-acdm', 'EdType_ Assoc-voc', 'EdType_ Bachelors', 'EdType_ Doctorate', 'EdType_ HS-grad', 'EdType_ Masters', 'EdType_ Preschool', 'EdType_ Prof-school', 'EdType_ Some-college', 'maritalstatus_ Married-AF-spouse', 'maritalstatus_ Married-civ-spouse', 'maritalstatus_ Married-spouse-absent', 'maritalstatus_ Never-married', 'maritalstatus_ Separated', 'maritalstatus_ Widowed', 'occupation_ Armed-Forces', 'occupation_ Craft-repair', 'occupation_ Exec-managerial', 'occupation_ Farming-fishing', 'occupation_ Handlers-cleaners', 'occupation_ Machine-op-inspct', 'occupation_ Other-service', 'occupation_ Priv-house-serv', 'occupation_ Prof-specialty', 'occupation_ Protective-s

In [25]:
features=list(set(columns_list)-set(['SalStat']))
print(features)

['nativecountry_ Thailand', 'EdType_ Doctorate', 'EdType_ Prof-school', 'nativecountry_ Philippines', 'maritalstatus_ Married-AF-spouse', 'maritalstatus_ Married-spouse-absent', 'age', 'occupation_ Prof-specialty', 'nativecountry_ Jamaica', 'nativecountry_ Germany', 'capitalloss', 'nativecountry_ Honduras', 'capitalgain', 'nativecountry_ Hungary', 'EdType_ 12th', 'nativecountry_ Scotland', 'nativecountry_ Columbia', 'relationship_ Own-child', 'nativecountry_ Guatemala', 'nativecountry_ Nicaragua', 'JobType_ Private', 'nativecountry_ Cuba', 'occupation_ Sales', 'occupation_ Machine-op-inspct', 'EdType_ 9th', 'JobType_ State-gov', 'nativecountry_ Vietnam', 'nativecountry_ South', 'occupation_ Protective-serv', 'EdType_ Assoc-voc', 'nativecountry_ India', 'hoursperweek', 'nativecountry_ Puerto-Rico', 'EdType_ Assoc-acdm', 'maritalstatus_ Never-married', 'occupation_ Exec-managerial', 'nativecountry_ France', 'EdType_ Some-college', 'nativecountry_ Portugal', 'nativecountry_ Peru', 'relati

In [26]:
y=new_data['SalStat'].values
print(y)

[0 0 1 ... 0 0 0]


In [27]:
x = new_data[features].values
print(x)

[[False False False ... False False False]
 [False False False ... False False False]
 [False False False ... False False False]
 ...
 [False False False ... False False False]
 [False False False ... False False False]
 [False False False ... False False False]]


In [28]:
train_x,test_x,train_y,test_y = train_test_split(x,y,test_size=0.3, random_state=0)

In [29]:
logistic = LogisticRegression()

In [30]:
# Fitting the values for x and y
logistic.fit(train_x,train_y)
logistic.coef_
logistic.intercept_

c:\Users\ruchi\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\linear_model\_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


array([-1.03974143])

In [31]:
prediction = logistic.predict(test_x)
print(prediction)

[0 0 0 ... 0 0 0]


In [32]:
confusion_matrix = confusion_matrix(test_y, prediction)
print(confusion_matrix)

[[6293  530]
 [ 954 1272]]


In [33]:
accuracy_score=accuracy_score(test_y, prediction)
print(accuracy_score)


0.8360039783401481


In [34]:
print('Misclassified samples: %d' % (test_y != prediction).sum())

Misclassified samples: 1484


In [35]:
# Reindexing the salary status names to 0,1
data3['SalStat']=data3['SalStat'].map({' less than or equal to 50,000':0,' greater than 50,000':1})
print(data3['SalStat'])


0        0
1        0
2        1
3        0
4        0
        ..
31973    0
31974    0
31975    0
31976    0
31977    0
Name: SalStat, Length: 30162, dtype: int64


In [36]:
cols = ['gender','nativecountry','race','JobType']
new_data = data3.drop(cols,axis = 1)

In [37]:
new_data=pd.get_dummies(new_data, drop_first=True)


In [38]:
# Storing the column names 
columns_list2=list(new_data.columns)
print(columns_list2)

['age', 'capitalgain', 'capitalloss', 'hoursperweek', 'SalStat', 'EdType_ 11th', 'EdType_ 12th', 'EdType_ 1st-4th', 'EdType_ 5th-6th', 'EdType_ 7th-8th', 'EdType_ 9th', 'EdType_ Assoc-acdm', 'EdType_ Assoc-voc', 'EdType_ Bachelors', 'EdType_ Doctorate', 'EdType_ HS-grad', 'EdType_ Masters', 'EdType_ Preschool', 'EdType_ Prof-school', 'EdType_ Some-college', 'maritalstatus_ Married-AF-spouse', 'maritalstatus_ Married-civ-spouse', 'maritalstatus_ Married-spouse-absent', 'maritalstatus_ Never-married', 'maritalstatus_ Separated', 'maritalstatus_ Widowed', 'occupation_ Armed-Forces', 'occupation_ Craft-repair', 'occupation_ Exec-managerial', 'occupation_ Farming-fishing', 'occupation_ Handlers-cleaners', 'occupation_ Machine-op-inspct', 'occupation_ Other-service', 'occupation_ Priv-house-serv', 'occupation_ Prof-specialty', 'occupation_ Protective-serv', 'occupation_ Sales', 'occupation_ Tech-support', 'occupation_ Transport-moving', 'relationship_ Not-in-family', 'relationship_ Other-rel

In [39]:
features2=list(set(columns_list2)-set(['SalStat']))
print(features2)

['occupation_ Other-service', 'EdType_ Doctorate', 'EdType_ Prof-school', 'occupation_ Tech-support', 'maritalstatus_ Married-AF-spouse', 'maritalstatus_ Married-spouse-absent', 'age', 'occupation_ Prof-specialty', 'relationship_ Unmarried', 'maritalstatus_ Married-civ-spouse', 'capitalloss', 'occupation_ Transport-moving', 'capitalgain', 'EdType_ 12th', 'EdType_ Bachelors', 'relationship_ Other-relative', 'relationship_ Own-child', 'EdType_ 7th-8th', 'occupation_ Farming-fishing', 'occupation_ Sales', 'occupation_ Machine-op-inspct', 'occupation_ Armed-Forces', 'EdType_ 9th', 'EdType_ 5th-6th', 'EdType_ Masters', 'maritalstatus_ Widowed', 'occupation_ Protective-serv', 'EdType_ 11th', 'EdType_ 1st-4th', 'EdType_ Assoc-voc', 'EdType_ HS-grad', 'EdType_ Preschool', 'relationship_ Wife', 'occupation_ Handlers-cleaners', 'occupation_ Craft-repair', 'EdType_ Assoc-acdm', 'maritalstatus_ Never-married', 'occupation_ Exec-managerial', 'EdType_ Some-college', 'occupation_ Priv-house-serv', 'r

In [40]:
y2=new_data['SalStat'].values
print(y2)

[0 0 1 ... 0 0 0]


In [41]:
# Storing the values from input features
x2 = new_data[features2].values
print(x2)

[[False False False ... True False 28]
 [False False False ... False False 40]
 [False False False ... False False 40]
 ...
 [False False False ... False False 40]
 [False False False ... False False 40]
 [False False False ... True False 40]]


In [42]:
train_x2,test_x2,train_y2,test_y2 = train_test_split(x2,y2,test_size=0.3, random_state=0)


In [43]:
logistic2 = LogisticRegression()

In [44]:
logistic2.fit(train_x2,train_y2)

c:\Users\ruchi\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\linear_model\_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [45]:
# Prediction from test data
prediction2 = logistic2.predict(test_x2)

In [46]:
print('Misclassified samples: %d' % (test_y2 != prediction2).sum())

Misclassified samples: 1504


In [47]:
import pandas as pd 

# To perform numerical operations
import numpy as np

# To visualize data
import seaborn as sns

# To partition the data
from sklearn.model_selection import train_test_split

# importing the library of KNN
from sklearn.neighbors import KNeighborsClassifier  

# Importing performance metrics - accuracy score & confusion matrix
from sklearn.metrics import accuracy_score,confusion_matrix

In [49]:
data = pd.read_csv(r'C:\Users\ruchi\Videos\Data_Science\nptel\income(1).csv',na_values=[" ?"])

In [50]:
data.isnull().sum()

age                 0
JobType          1809
EdType              0
maritalstatus       0
occupation       1816
relationship        0
race                0
gender              0
capitalgain         0
capitalloss         0
hoursperweek        0
nativecountry       0
SalStat             0
dtype: int64

In [51]:
missing = data[data.isnull().any(axis=1)]

In [52]:
data2 = data.dropna(axis=0)

In [53]:
data2['SalStat']=data2['SalStat'].map({' less than or equal to 50,000':0,' greater than 50,000':1})
print(data2['SalStat'])

0        0
1        0
2        1
3        0
4        0
        ..
31973    0
31974    0
31975    0
31976    0
31977    0
Name: SalStat, Length: 30162, dtype: int64


C:\Users\ruchi\AppData\Local\Temp\ipykernel_15892\784685041.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data2['SalStat']=data2['SalStat'].map({' less than or equal to 50,000':0,' greater than 50,000':1})


In [54]:
new_data=pd.get_dummies(data2, drop_first=True)

In [55]:
columns_list=list(new_data.columns)
print(columns_list)

['age', 'capitalgain', 'capitalloss', 'hoursperweek', 'SalStat', 'JobType_ Local-gov', 'JobType_ Private', 'JobType_ Self-emp-inc', 'JobType_ Self-emp-not-inc', 'JobType_ State-gov', 'JobType_ Without-pay', 'EdType_ 11th', 'EdType_ 12th', 'EdType_ 1st-4th', 'EdType_ 5th-6th', 'EdType_ 7th-8th', 'EdType_ 9th', 'EdType_ Assoc-acdm', 'EdType_ Assoc-voc', 'EdType_ Bachelors', 'EdType_ Doctorate', 'EdType_ HS-grad', 'EdType_ Masters', 'EdType_ Preschool', 'EdType_ Prof-school', 'EdType_ Some-college', 'maritalstatus_ Married-AF-spouse', 'maritalstatus_ Married-civ-spouse', 'maritalstatus_ Married-spouse-absent', 'maritalstatus_ Never-married', 'maritalstatus_ Separated', 'maritalstatus_ Widowed', 'occupation_ Armed-Forces', 'occupation_ Craft-repair', 'occupation_ Exec-managerial', 'occupation_ Farming-fishing', 'occupation_ Handlers-cleaners', 'occupation_ Machine-op-inspct', 'occupation_ Other-service', 'occupation_ Priv-house-serv', 'occupation_ Prof-specialty', 'occupation_ Protective-s

In [56]:
features=list(set(columns_list)-set(['SalStat']))
print(features)

['nativecountry_ Thailand', 'EdType_ Doctorate', 'EdType_ Prof-school', 'nativecountry_ Philippines', 'maritalstatus_ Married-AF-spouse', 'maritalstatus_ Married-spouse-absent', 'age', 'occupation_ Prof-specialty', 'nativecountry_ Jamaica', 'nativecountry_ Germany', 'capitalloss', 'nativecountry_ Honduras', 'capitalgain', 'nativecountry_ Hungary', 'EdType_ 12th', 'nativecountry_ Scotland', 'nativecountry_ Columbia', 'relationship_ Own-child', 'nativecountry_ Guatemala', 'nativecountry_ Nicaragua', 'JobType_ Private', 'nativecountry_ Cuba', 'occupation_ Sales', 'occupation_ Machine-op-inspct', 'EdType_ 9th', 'JobType_ State-gov', 'nativecountry_ Vietnam', 'nativecountry_ South', 'occupation_ Protective-serv', 'EdType_ Assoc-voc', 'nativecountry_ India', 'hoursperweek', 'nativecountry_ Puerto-Rico', 'EdType_ Assoc-acdm', 'maritalstatus_ Never-married', 'occupation_ Exec-managerial', 'nativecountry_ France', 'EdType_ Some-college', 'nativecountry_ Portugal', 'nativecountry_ Peru', 'relati

In [57]:
y=new_data['SalStat'].values
print(y)

[0 0 1 ... 0 0 0]


In [58]:
x = new_data[features].values
print(x)

[[False False False ... False False False]
 [False False False ... False False False]
 [False False False ... False False False]
 ...
 [False False False ... False False False]
 [False False False ... False False False]
 [False False False ... False False False]]


In [59]:
train_x,test_x,train_y,test_y = train_test_split(x,y,test_size=0.3, random_state=0)

In [60]:
KNN_classifier = KNeighborsClassifier(n_neighbors = 5)  

In [61]:
KNN_classifier.fit(train_x, train_y) 

KNeighborsClassifier()

In [62]:
# Predicting the test values with model
prediction = KNN_classifier.predict(test_x)

In [63]:
confusionMmatrix = confusion_matrix(test_y, prediction)
print(confusionMmatrix)

[[6176  647]
 [ 808 1418]]


In [64]:
accuracy_score=accuracy_score(test_y, prediction)
print(accuracy_score)

0.8392087523483258


In [65]:
print('Misclassified samples: %d' % (test_y != prediction).sum())


Misclassified samples: 1455


In [66]:
Misclassified_sample = []

In [67]:
# Calculating error for K values between 1 and 20
for i in range(1, 20):  
    knn = KNeighborsClassifier(n_neighbors=i)
    knn.fit(train_x, train_y)
    pred_i = knn.predict(test_x)
    Misclassified_sample.append((test_y != pred_i).sum())

print(Misclassified_sample)

[np.int64(1766), np.int64(1516), np.int64(1522), np.int64(1437), np.int64(1455), np.int64(1455), np.int64(1456), np.int64(1452), np.int64(1481), np.int64(1432), np.int64(1465), np.int64(1446), np.int64(1451), np.int64(1435), np.int64(1421), np.int64(1415), np.int64(1435), np.int64(1423), np.int64(1443)]
