##### Sequence datatype object initializations

In [2]:
strSample = 'leaning is fun !'

In [3]:
lstSample = [1,2,'a','sam',2]

In [4]:
from array import *

In [5]:
arrSample = array('i',[1,2,3,4])

In [6]:
tupSample = (1,2,3,4,3,'py')

In [7]:
dictSample = {1:'first', 'second':2, 3:3, 'four':4}

In [8]:
setSample = {'example',24,87.5,'data',24,'data'}
keys = (1,'second',3,'four')
rangeSample = range(1,12,4)
for x in rangeSample: print(x)

1
5
9


##### len(object)

In [9]:
print("No. of elements in the object :")

print("string = {}, list={}, array={}, tuple ={},\
    dictionary={}, set = {}, range={}".format(len(strSample),len(lstSample),len(arrSample),len(tupSample),len(dictSample),len(setSample),len(rangeSample)))

No. of elements in the object :
string = 16, list=5, array=4, tuple =6,    dictionary=4, set = 4, range=3


In [10]:
lstSample.reverse()
print(lstSample)

[2, 'sam', 'a', 2, 1]


##### clear()
only supported by:
* list
* dictionary
* set

In [11]:
lstSample.clear()
print(lstSample)

[]


In [12]:
dictSample.clear()
print(dictSample)

{}


In [13]:
setSample.clear()
print(setSample)

set()


##### append()
* Array
* List
* set

In [14]:
arrSample.append(3)
print(arrSample)

array('i', [1, 2, 3, 4, 3])


In [15]:
lstSample = [1,2,'a','sam',2]

In [16]:
lstSample.append([2,4])
print(lstSample)

[1, 2, 'a', 'sam', 2, [2, 4]]


In [17]:
setSample = {1,2,3,4,5,3,2,1}
setSample.add(20) #.append() not supported by set #.add() can only take single value at a time
print(setSample)

{1, 2, 3, 4, 5, 20}


##### Update() function in set adds elements from a set (passed as an argument) to the set
* method takes only single argument
* that single argument can be set, list, tuple, dictionary
* It automatically converts into a set and adds to the set


In [18]:
setSample.update([5,10])
print(setSample)

{1, 2, 3, 4, 5, 20, 10}


##### Dictionary Methods

In [19]:
dictSample = {1:'first', 'second':2, 3:3, 'four':4}
print(dictSample)

{1: 'first', 'second': 2, 3: 3, 'four': 4}


In [20]:
dictSample['five'] = 5
print(dictSample)

{1: 'first', 'second': 2, 3: 3, 'four': 4, 'five': 5}


In [24]:
dictSample.update(five = 5)
print(dictSample)

{1: 'first', 'second': 2, 3: 3, 'four': 4, 'five': 5}


In [ ]:
list(dictSample) #returns list of all the keys

[1, 'second', 3, 'four', 'five']

In [25]:
len(dictSample)

5

In [26]:
dictSample.get("five")

5

In [27]:
dictSample.keys()

dict_keys([1, 'second', 3, 'four', 'five'])

In [28]:
dictSample.items()

dict_items([(1, 'first'), ('second', 2), (3, 3), ('four', 4), ('five', 5)])

insert()- insert the element at the specified index of the object
* supported datatypes array, list

In [29]:
print(arrSample)

array('i', [1, 2, 3, 4, 3])


In [ ]:
arrSample.insert(1,100) #.insert(position, value)
print(arrSample)

array('i', [1, 100, 2, 3, 4, 3])


In [32]:
lstSample.insert(5,24)
print(lstSample)

[1, 2, 'a', 'sam', 2, 24, 24, [2, 4]]


pop() - remove the element at the given index from the object and prints the same

* default value is -1, which returns the last item
* support datatype: array, list, set, dictionary

In [33]:
arrSample.pop() 

3

In [34]:
print(lstSample)
lstSample.pop(4)

[1, 2, 'a', 'sam', 2, 24, 24, [2, 4]]


2

In [35]:
print(dictSample)
dictSample.pop('second')

{1: 'first', 'second': 2, 3: 3, 'four': 4, 'five': 5}


2

In [36]:
print(dictSample)

{1: 'first', 3: 3, 'four': 4, 'five': 5}


In [37]:
dictSample.pop(3)

3

Set is an unorders sequence and hence pop is not used

The remove() method removes the first occurrence of the element with the specified value
* supported by array, list, dictionary, set

In [38]:
print(arrSample)

array('i', [1, 100, 2, 3, 4])


In [39]:
arrSample.remove(0)

ValueError: array.remove(x): x not in array

In [40]:
arrSample.remove(2)
print(arrSample)

array('i', [1, 100, 3, 4])


In [41]:
print(lstSample)
lstSample.remove('sam')
print(lstSample)

[1, 2, 'a', 'sam', 24, 24, [2, 4]]
[1, 2, 'a', 24, 24, [2, 4]]


In [42]:
print(setSample)
setSample.remove(57)

{1, 2, 3, 4, 5, 20, 10}


KeyError: 57

In [43]:
setSample.discard(57)
print(setSample)


{1, 2, 3, 4, 5, 20, 10}


del: delete the entire object of any data type
* syntax: del obj_name
* del is a Python keyword
* obj_name can be variable, user-defined objects, lists, items within lists, dictionary etc.

In [48]:
del setSample
print(setSample)


NameError: name 'setSample' is not defined

In [49]:
del arrSample
print(arrSample)

NameError: name 'arrSample' is not defined

In [50]:
del lstSample[2]
print(lstSample)

[1, 2, 24, 24, [2, 4]]


In [51]:
del lstSample[1:3]
print(lstSample)

[1, 24, [2, 4]]


In [52]:
del lstSample[:]
print(lstSample)

[]


In [53]:
del dictSample
print(dictSample)

NameError: name 'dictSample' is not defined

The extend() method adds the specified list elements (or any iterable - list, set,tuple, etc) to the end of the current list

Array oprations

In [58]:
from array import *
arrSample = array('i',[1,2,3,4])
arrSample.extend((4,5,3,5))
print(arrSample)

array('i', [1, 2, 3, 4, 4, 5, 3, 5])


In [59]:
print(arrSample.extend(['sam']))

TypeError: 'str' object cannot be interpreted as an integer

In [60]:
arrSample.fromlist([3,4])
print(arrSample)

arrSample.tolist()

array('i', [1, 2, 3, 4, 4, 5, 3, 5, 3, 4])


[1, 2, 3, 4, 4, 5, 3, 5, 3, 4]

#### setSample
Sets can be used to perform mathematical set operation like union, intersection, symmetric difference etc

In [61]:
A = {'example',24,87.5,'data',24,'data'}
print(A)

{24, 'example', 'data', 87.5}


In [62]:
B = {24,87.5}
B

{24, 87.5}

In [63]:
print(A | B)
A.union(B)

{87.5, 24, 'example', 'data'}


{24, 87.5, 'data', 'example'}

In [64]:
print(A & B)
A.intersection(B)

{24, 87.5}


{24, 87.5}

# <b>Numpy</b>

In [65]:
my_list = [1, 2, 3,4, 5,6]
print(my_list)

[1, 2, 3, 4, 5, 6]


In [67]:
import numpy as np

In [68]:
array = np.array(my_list, dtype = int)
print(array)

[1 2 3 4 5 6]


In [71]:
print(type(array))
print(len(array))
print(array.ndim)
print(array.shape)

<class 'numpy.ndarray'>
6
1
(6,)


In [72]:
array2 = array.reshape(3,2)
print(array2)
array2.shape

[[1 2]
 [3 4]
 [5 6]]


(3, 2)

In [74]:
array3 = array.reshape(3,-1)
print(array3)

print(array3.ndim)

[[1 2]
 [3 4]
 [5 6]]
2


In [75]:
my_list2 = [1,2,3,4,5]
my_list3 = [2,3,4,5,6]
my_list4 = [9,7,6,8,9]

mul_arr = np.array([my_list2, my_list3, my_list4])
print(mul_arr)

print(mul_arr.shape)

[[1 2 3 4 5]
 [2 3 4 5 6]
 [9 7 6 8 9]]
(3, 5)


In [76]:
mul_arr.reshape(1,15)

array([[1, 2, 3, 4, 5, 2, 3, 4, 5, 6, 9, 7, 6, 8, 9]])

In [77]:
r = range(24)

In [78]:
print(r)

range(0, 24)


In [80]:
a = np.arange(24)
print(a)
print(a.ndim)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
1


In [81]:
b = a.reshape(6,4,1)
print(b)

[[[ 0]
  [ 1]
  [ 2]
  [ 3]]

 [[ 4]
  [ 5]
  [ 6]
  [ 7]]

 [[ 8]
  [ 9]
  [10]
  [11]]

 [[12]
  [13]
  [14]
  [15]]

 [[16]
  [17]
  [18]
  [19]]

 [[20]
  [21]
  [22]
  [23]]]


In [82]:
x = np.array([[1,2],[3,4]], dtype = np.float64)
y = np.array([[5,6],[7,8]], dtype = np.float64)
print(x)
print(y)

[[1. 2.]
 [3. 4.]]
[[5. 6.]
 [7. 8.]]


In [83]:
print(x+y)
print(np.add(x,y)) 

[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]


In [84]:
print(x-y)
print(np.subtract(x,y))

[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]


In [85]:
print(x*y)
print(np.multiply(x,y))

[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]


In [86]:
print(x.dot(y))
print(np.dot(x,y))

[[19. 22.]
 [43. 50.]]
[[19. 22.]
 [43. 50.]]


In [87]:
print(x/y)
print(np.divide(x,y))

[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [88]:
print(np.sum(x))
print(x)

10.0
[[1. 2.]
 [3. 4.]]


In [ ]:
print(np.sum(x, axis=0)) # comuptes the sum of each column

[4. 6.]


In [90]:
print(np.sum(x, axis=1)) 

[3. 7.]
