# Logistic Regression Implementation

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [2]:
from sklearn.datasets import make_classification


In [3]:
X,y=make_classification(n_samples=1000, n_features=10, n_classes=2, random_state=4)

In [4]:
pd.DataFrame(X).head()

,0,1,2,3,4,5,6,7,8,9
0,-0.882985,0.633832,1.253856,1.497910,-1.471741,-0.043645,0.666871,-0.604995,0.305191,0.093921
1,-1.859469,1.204137,-0.097952,-1.248213,-0.631883,-0.674766,-1.443463,0.512446,2.070805,-0.692653
2,0.574556,-0.079292,-0.401556,1.108514,-0.736020,0.428477,1.520842,0.027460,0.379514,-0.804973
3,0.009995,-0.193855,1.050033,0.776469,-0.876279,0.211422,1.023044,-1.451348,-1.019582,-0.285256
4,-0.741163,0.576542,-1.968547,0.771841,-1.570519,0.042537,0.946593,-1.626563,1.736183,1.050014


In [5]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.30, random_state=42)

In [6]:
#Model training
from sklearn.linear_model import LogisticRegression
logistic = LogisticRegression()

In [7]:
logistic.fit(X_train, y_train)

LogisticRegression()

In [8]:
y_pred = logistic.predict(X_test)
print(y_pred)

[1 1 0 1 0 0 0 1 0 0 1 0 0 1 1 0 0 0 1 0 0 1 0 0 1 1 1 0 0 0 0 1 0 1 0 1 1
 0 1 1 0 1 1 0 0 0 1 0 0 0 1 0 1 1 1 1 1 0 0 1 0 0 1 1 0 0 1 1 0 0 0 1 1 0
 0 1 0 1 0 0 0 0 0 0 1 1 0 1 0 1 1 1 1 0 1 0 0 1 1 0 0 0 1 1 0 1 0 0 0 0 1
 0 1 0 1 0 0 0 1 0 0 1 0 1 0 0 0 1 1 0 0 1 1 0 1 0 0 1 0 1 0 1 0 1 1 1 0 1
 1 0 0 1 0 0 0 0 1 0 1 0 1 0 0 1 1 0 1 0 1 0 0 0 1 0 0 1 0 0 0 1 1 1 1 0 1
 1 1 0 0 1 0 0 0 1 0 0 0 1 1 1 0 0 0 1 1 1 1 1 1 1 1 0 0 0 1 1 0 0 1 0 1 0
 1 1 1 1 0 1 1 0 0 1 1 1 1 1 1 0 1 1 1 0 0 0 1 1 1 0 1 0 0 1 1 0 1 1 0 1 0
 0 1 1 1 1 1 0 0 0 1 1 0 0 0 1 1 0 0 1 1 0 1 1 0 0 0 1 1 0 1 1 1 1 1 0 0 0
 0 0 0 0]


In [9]:
logistic.predict_proba(X_test)

array([[1.78915007e-01, 8.21084993e-01],
       [1.44553509e-01, 8.55446491e-01],
       [6.51227377e-01, 3.48772623e-01],
       [2.50735696e-01, 7.49264304e-01],
       [9.80040683e-01, 1.99593170e-02],
       [9.99681628e-01, 3.18372115e-04],
       [6.00275183e-01, 3.99724817e-01],
       [7.13510737e-02, 9.28648926e-01],
       [9.96939062e-01, 3.06093770e-03],
       [5.35551353e-01, 4.64448647e-01],
       [3.32365422e-01, 6.67634578e-01],
       [9.99986308e-01, 1.36915519e-05],
       [9.47602465e-01, 5.23975346e-02],
       [3.87500385e-02, 9.61249961e-01],
       [1.28330106e-01, 8.71669894e-01],
       [6.01058249e-01, 3.98941751e-01],
       [9.94258472e-01, 5.74152757e-03],
       [8.95751399e-01, 1.04248601e-01],
       [1.04500008e-01, 8.95499992e-01],
       [8.58629435e-01, 1.41370565e-01],
       [9.94969734e-01, 5.03026569e-03],
       [9.09873621e-05, 9.99909013e-01],
       [9.86592391e-01, 1.34076094e-02],
       [9.96605533e-01, 3.39446718e-03],
       [6.680931

In [10]:
from sklearn.metrics import accuracy_score,confusion_matrix, classification_report

In [11]:
score= accuracy_score(y_test,y_pred)
print(score)
cm= confusion_matrix(y_test,y_pred)
print(cm)
cr= classification_report(y_test,y_pred)
print(cr)

0.9
[[143  19]
 [ 11 127]]
              precision    recall  f1-score   support

           0       0.93      0.88      0.91       162
           1       0.87      0.92      0.89       138

    accuracy                           0.90       300
   macro avg       0.90      0.90      0.90       300
weighted avg       0.90      0.90      0.90       300



# Hyperparameter Tuning

#### GridSearchCV

In [12]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression

pipe = Pipeline([
    ('scaler', StandardScaler()),
    ('logreg', LogisticRegression(max_iter=10000))
])


In [13]:
param_grid = {
    'logreg__solver': ['saga'],
    'logreg__penalty': ['l1', 'l2', 'elasticnet'],
    'logreg__C': [100, 10, 1.0, 0.1, 0.01],
    'logreg__l1_ratio': [0.5]   # required for elasticnet
}


In [14]:
from sklearn.model_selection import StratifiedKFold

cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)


In [15]:
from sklearn.model_selection import GridSearchCV

grid = GridSearchCV(
    estimator=pipe,
    param_grid=param_grid,
    scoring='accuracy',
    cv=cv,
    n_jobs=-1,
    error_score='raise'  # forces crash if something is wrong
)

grid.fit(X_train, y_train)


GridSearchCV(cv=StratifiedKFold(n_splits=5, random_state=42, shuffle=True),
             error_score='raise',
             estimator=Pipeline(steps=[('scaler', StandardScaler()),
                                       ('logreg',
                                        LogisticRegression(max_iter=10000))]),
             n_jobs=-1,
             param_grid={'logreg__C': [100, 10, 1.0, 0.1, 0.01],
                         'logreg__l1_ratio': [0.5],
                         'logreg__penalty': ['l1', 'l2', 'elasticnet'],
                         'logreg__solver': ['saga']},
             scoring='accuracy')

In [16]:
print("Best Parameters:", grid.best_params_)
print("Best CV Score:", grid.best_score_)


Best Parameters: {'logreg__C': 0.1, 'logreg__l1_ratio': 0.5, 'logreg__penalty': 'elasticnet', 'logreg__solver': 'saga'}
Best CV Score: 0.9028571428571428


In [17]:
grid.fit(X_train,y_train)

GridSearchCV(cv=StratifiedKFold(n_splits=5, random_state=42, shuffle=True),
             error_score='raise',
             estimator=Pipeline(steps=[('scaler', StandardScaler()),
                                       ('logreg',
                                        LogisticRegression(max_iter=10000))]),
             n_jobs=-1,
             param_grid={'logreg__C': [100, 10, 1.0, 0.1, 0.01],
                         'logreg__l1_ratio': [0.5],
                         'logreg__penalty': ['l1', 'l2', 'elasticnet'],
                         'logreg__solver': ['saga']},
             scoring='accuracy')

In [18]:
from sklearn.metrics import accuracy_score

y_pred = grid.predict(X_test)
print("Test Accuracy:", accuracy_score(y_test, y_pred))


Test Accuracy: 0.9


### Randomized SearchCV

In [20]:
from sklearn.model_selection import RandomizedSearchCV
from sklearn.linear_model import LogisticRegression


In [21]:
model = LogisticRegression()

params = {
    'C': [0.1, 1, 10],
    'penalty': ['l1', 'l2'],
    'solver': ['liblinear']
}

randomcv = RandomizedSearchCV(
    estimator=model,
    param_distributions=params,
    cv=5,
    scoring='accuracy'
)

randomcv.fit(X_train, y_train)


c:\Users\ruchi\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\model_selection\_search.py:317: UserWarning: The total space of parameters 6 is smaller than n_iter=10. Running 6 iterations. For exhaustive searches, use GridSearchCV.
  warnings.warn(


RandomizedSearchCV(cv=5, estimator=LogisticRegression(),
                   param_distributions={'C': [0.1, 1, 10],
                                        'penalty': ['l1', 'l2'],
                                        'solver': ['liblinear']},
                   scoring='accuracy')

In [22]:
randomcv.best_score_

np.float64(0.9042857142857142)

In [23]:
randomcv.best_params_

{'solver': 'liblinear', 'penalty': 'l2', 'C': 0.1}

In [24]:
y_prid =  randomcv.predict(X_test)

In [25]:
score= accuracy_score(y_test,y_pred)
print(score)
cm= confusion_matrix(y_test,y_pred)
print(cm)
cr= classification_report(y_test,y_pred)
print(cr)

0.9
[[142  20]
 [ 10 128]]
              precision    recall  f1-score   support

           0       0.93      0.88      0.90       162
           1       0.86      0.93      0.90       138

    accuracy                           0.90       300
   macro avg       0.90      0.90      0.90       300
weighted avg       0.90      0.90      0.90       300



# Logistic Regression For Multiclass Classification Probelm

In [27]:
X,y=make_classification(n_samples=1000, n_features=10, n_informative=3, n_classes=3, random_state=4)

In [28]:
y

array([2, 2, 2, 1, 0, 1, 0, 2, 1, 2, 0, 2, 1, 1, 2, 2, 1, 0, 2, 1, 2, 2,
       0, 0, 2, 1, 1, 1, 1, 2, 2, 2, 2, 2, 1, 0, 1, 1, 2, 1, 2, 1, 0, 2,
       0, 2, 0, 2, 0, 1, 0, 2, 0, 0, 2, 1, 2, 1, 2, 2, 0, 1, 2, 2, 2, 0,
       2, 2, 0, 2, 0, 1, 1, 1, 1, 1, 2, 1, 0, 2, 1, 2, 1, 0, 2, 2, 0, 2,
       1, 1, 1, 2, 1, 1, 0, 1, 2, 1, 1, 2, 1, 2, 2, 2, 0, 1, 2, 2, 1, 1,
       2, 1, 1, 0, 1, 2, 0, 0, 0, 2, 1, 0, 2, 1, 0, 1, 0, 2, 0, 1, 1, 1,
       1, 2, 1, 1, 1, 2, 0, 2, 0, 1, 2, 1, 2, 2, 1, 0, 1, 0, 0, 2, 0, 0,
       1, 2, 1, 2, 1, 1, 1, 1, 1, 2, 0, 0, 1, 0, 1, 0, 2, 2, 2, 1, 1, 1,
       0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 2, 0, 0, 2, 1, 1, 0, 1, 2, 1,
       2, 1, 1, 1, 1, 0, 2, 0, 0, 0, 1, 0, 1, 2, 0, 0, 1, 2, 0, 1, 1, 0,
       2, 2, 0, 2, 2, 0, 1, 2, 1, 2, 0, 2, 2, 1, 0, 0, 2, 1, 2, 0, 0, 2,
       2, 0, 1, 1, 1, 0, 1, 1, 1, 2, 1, 1, 1, 0, 0, 0, 2, 0, 2, 0, 2, 1,
       2, 1, 0, 1, 0, 2, 1, 2, 0, 2, 1, 2, 2, 2, 0, 0, 2, 0, 0, 2, 0, 1,
       0, 2, 1, 2, 1, 2, 0, 0, 1, 2, 1, 0, 0, 1, 0,

In [29]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.30, random_state=42)

In [31]:
from sklearn.linear_model import LogisticRegression
logistic = LogisticRegression(multi_class='ovr')
logistic.fit(X_train,y_train)
y_pred = logistic.predict(X_test)

c:\Users\ruchi\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\linear_model\_logistic.py:1256: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. Use OneVsRestClassifier(LogisticRegression(..)) instead. Leave it to its default value to avoid this warning.
  warnings.warn(


In [32]:
y_pred

array([1, 1, 2, 0, 0, 0, 2, 1, 0, 2, 1, 1, 0, 1, 0, 2, 2, 2, 1, 0, 0, 0,
       2, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 2, 1, 2, 2, 0, 2, 0, 2, 0, 2,
       0, 2, 0, 1, 1, 2, 2, 0, 0, 1, 0, 2, 2, 0, 1, 1, 2, 1, 0, 0, 0, 2,
       0, 0, 0, 1, 1, 2, 1, 2, 0, 1, 2, 1, 0, 1, 0, 0, 2, 1, 1, 2, 0, 2,
       0, 1, 0, 1, 0, 2, 2, 0, 2, 2, 0, 1, 0, 2, 2, 0, 0, 1, 2, 1, 0, 1,
       0, 1, 0, 2, 0, 1, 2, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 2, 0, 0, 1, 2,
       2, 2, 0, 2, 2, 2, 1, 1, 0, 0, 2, 0, 2, 2, 0, 1, 0, 2, 2, 2, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 1, 0, 1, 0,
       2, 0, 2, 1, 0, 2, 1, 0, 1, 0, 2, 0, 2, 0, 0, 2, 2, 1, 0, 2, 0, 1,
       1, 0, 1, 2, 2, 0, 2, 0, 0, 0, 0, 0, 0, 2, 1, 0, 1, 2, 0, 2, 0, 1,
       1, 0, 0, 1, 2, 0, 2, 1, 2, 2, 0, 1, 1, 2, 0, 2, 2, 0, 2, 0, 1, 0,
       0, 0, 0, 1, 2, 0, 1, 0, 1, 2, 1, 1, 2, 2, 2, 2, 0, 2, 0, 0, 2, 0,
       1, 2, 0, 1, 1, 1, 0, 0, 1, 2, 2, 1, 1, 1, 1, 1, 1, 0, 0, 0, 2, 2,
       0, 0, 2, 0, 1, 2, 1, 0, 2, 2, 0, 2, 1, 2])

In [33]:
score= accuracy_score(y_test,y_pred)
print(score)
cm= confusion_matrix(y_test,y_pred)
print(cm)
cr= classification_report(y_test,y_pred)
print(cr)

0.57
[[93  3  3]
 [15 37 47]
 [19 42 41]]
              precision    recall  f1-score   support

           0       0.73      0.94      0.82        99
           1       0.45      0.37      0.41        99
           2       0.45      0.40      0.42       102

    accuracy                           0.57       300
   macro avg       0.54      0.57      0.55       300
weighted avg       0.54      0.57      0.55       300

